-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 13:50:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LebedkinAnatolijBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Country` ;

CREATE TABLE IF NOT EXISTS `Country` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));
-- -----------------------------------------------------
-- Table `Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cities` ;

CREATE TABLE IF NOT EXISTS `Cities` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Country` INT NULL,
  PRIMARY KEY (`ID`),
    FOREIGN KEY (`Country`)
    REFERENCES `Country` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `Adresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adresses` ;

CREATE TABLE IF NOT EXISTS `Adresses` (
  `ID` INT NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `City` INT NULL,
  PRIMARY KEY (`ID`),
    FOREIGN KEY (`City`)
    REFERENCES `Cities` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table `Makers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Makers` ;

CREATE TABLE IF NOT EXISTS `Makers` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adress` INT NULL,
  PRIMARY KEY (`ID`),
    FOREIGN KEY (`Adress`)
    REFERENCES `Adresses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
-- -----------------------------------------------------
-- Table `Storage_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Storage_time` ;

CREATE TABLE IF NOT EXISTS `Storage_time` (
  `ID` INT NOT NULL,
  `Storage time` INT NOT NULL,
  PRIMARY KEY (`ID`));
-- -----------------------------------------------------
-- Table `Medicine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicine` ;

CREATE TABLE IF NOT EXISTS `Medicine` (
  `ID` INT NOT NULL,
  `Medical name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));
-- -----------------------------------------------------
-- Table `Drugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Drugs` ;

CREATE TABLE IF NOT EXISTS `Drugs` (
  `ID` INT NULL,
  `Name` VARCHAR(45) NULL,
  `Image` VARCHAR(45) NULL,
  `Maker` INT NULL,
  `Storage time` INT NULL,
  `Medicine` INT NULL,
  PRIMARY KEY (`ID`),
    FOREIGN KEY (`Maker`)
    REFERENCES `Makers` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    FOREIGN KEY (`Storage time`)
    REFERENCES `Storage_time` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    FOREIGN KEY (`Medicine`)
    REFERENCES `Medicine` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);
-- -----------------------------------------------------
-- Table `Distributers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distributers` ;

CREATE TABLE IF NOT EXISTS `Distributers` (
  `ID` INT NOT NULL,
  `INN` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adress` INT NULL,
  PRIMARY KEY (`ID`, `INN`),
    FOREIGN KEY (`Adress`)
    REFERENCES `Adresses` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);
-- -----------------------------------------------------
-- Table `Supply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply` ;

CREATE TABLE IF NOT EXISTS `Supply` (
  `ID` INT NOT NULL,
  `Date` DATE NULL,
  `Destributor` INT NULL,
  PRIMARY KEY (`ID`),
    FOREIGN KEY (`Destributor`)
    REFERENCES `Distributers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
-- -----------------------------------------------------
-- Table `Suppliment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Suppliment` ;

CREATE TABLE IF NOT EXISTS `Suppliment` (
  `Supply` INT NOT NULL,
  `Drug` INT NULL,
  `Price` INT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`Supply`),
    FOREIGN KEY (`Supply`)
    REFERENCES `Supply` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`Drug`)
    REFERENCES `Drugs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
-- -----------------------------------------------------
-- Table `Check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check` ;

CREATE TABLE IF NOT EXISTS `Check` (
  `ID` INT NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`ID`));
-- -----------------------------------------------------
-- Table `Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales` ;

CREATE TABLE IF NOT EXISTS `Sales` (
  `Check` INT NOT NULL,
  `Drug` INT NOT NULL,
  `Price` INT NULL ,
  `Quantity` INT NULL,
  PRIMARY KEY (`Check`, `Drug`),
    FOREIGN KEY (`Check`)
    REFERENCES `Check` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`Drug`)
    REFERENCES `Drugs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
-- -----------------------------------------------------
-- Table `Storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Storage` ;

CREATE TABLE IF NOT EXISTS `Storage` (
  `Drug` INT NOT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`Drug`),
    FOREIGN KEY (`Drug`)
    REFERENCES `Drugs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

