-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 13:50:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LebedkinAnatolijBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Country` ;

CREATE TABLE IF NOT EXISTS `Country` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cities` ;

CREATE TABLE IF NOT EXISTS `Cities` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Country` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Country`
    FOREIGN KEY (`Country`)
    REFERENCES `Country` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `Country_idx` ON `Cities` (`Country` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Adresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adresses` ;

CREATE TABLE IF NOT EXISTS `Adresses` (
  `ID` INT NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `City` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `CITY`
    FOREIGN KEY (`City`)
    REFERENCES `Cities` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `ID_idx` ON `Adresses` (`City` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Makers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Makers` ;

CREATE TABLE IF NOT EXISTS `Makers` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adress` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Adress`
    FOREIGN KEY (`Adress`)
    REFERENCES `Adresses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Adress_idx` ON `Makers` (`Adress` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Storage_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Storage_time` ;

CREATE TABLE IF NOT EXISTS `Storage_time` (
  `ID` INT NOT NULL,
  `Storage time` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medicine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicine` ;

CREATE TABLE IF NOT EXISTS `Medicine` (
  `ID` INT NOT NULL,
  `Medical name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Drugs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Drugs` ;

CREATE TABLE IF NOT EXISTS `Drugs` (
  `ID` INT NULL,
  `Name` VARCHAR(45) NULL,
  `Image` VARCHAR(45) NULL,
  `Maker` INT NULL,
  `Storage time` INT NULL,
  `Medicine` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Maker`
    FOREIGN KEY (`Maker`)
    REFERENCES `Makers` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Storage time`
    FOREIGN KEY (`Storage time`)
    REFERENCES `Storage_time` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Medicine`
    FOREIGN KEY (`Medicine`)
    REFERENCES `Medicine` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `Maker_idx` ON `Drugs` (`Maker` ASC) VISIBLE;

CREATE INDEX `Medicine_idx` ON `Drugs` (`Medicine` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Distributers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Distributers` ;

CREATE TABLE IF NOT EXISTS `Distributers` (
  `ID` INT NOT NULL,
  `INN` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Adress` INT NULL,
  PRIMARY KEY (`ID`, `INN`),
  CONSTRAINT `Adress`
    FOREIGN KEY (`Adress`)
    REFERENCES `Adresses` (`ID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `Adress_idx` ON `Distributers` (`Adress` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Supply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Supply` ;

CREATE TABLE IF NOT EXISTS `Supply` (
  `ID` INT NOT NULL,
  `Date` DATE NULL,
  `Destributor` INT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Distributor`
    FOREIGN KEY (`Destributor`)
    REFERENCES `Distributers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Distributor_idx` ON `Supply` (`Destributor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Suppliment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Suppliment` ;

CREATE TABLE IF NOT EXISTS `Suppliment` (
  `Supply` INT NOT NULL,
  `Drug` INT NULL,
  `Price` INT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`Supply`),
  CONSTRAINT `Supply`
    FOREIGN KEY (`Supply`)
    REFERENCES `Supply` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Drug`
    FOREIGN KEY (`Drug`)
    REFERENCES `Drugs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';

CREATE INDEX `Drug_idx` ON `Suppliment` (`Drug` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check` ;

CREATE TABLE IF NOT EXISTS `Check` (
  `ID` INT NOT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales` ;

CREATE TABLE IF NOT EXISTS `Sales` (
  `Check` INT NOT NULL,
  `Drug` INT NOT NULL,
  `Price` INT NULL COMMENT 'Suppliment price+Drugstore profit',
  `Quantity` INT NULL,
  PRIMARY KEY (`Check`, `Drug`),
  CONSTRAINT `Check`
    FOREIGN KEY (`Check`)
    REFERENCES `Check` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Drug`
    FOREIGN KEY (`Drug`)
    REFERENCES `Drugs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Drug_idx` ON `Sales` (`Drug` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Storage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Storage` ;

CREATE TABLE IF NOT EXISTS `Storage` (
  `Drug` INT NOT NULL,
  `Quantity` INT NULL COMMENT 'Suppliment.quantity-sales.quantity',
  PRIMARY KEY (`Drug`),
  CONSTRAINT `Drug`
    FOREIGN KEY (`Drug`)
    REFERENCES `Drugs` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


DELIMITER $$

DROP TRIGGER IF EXISTS `Sales_AFTER_INSERT` $$
CREATE DEFINER = CURRENT_USER TRIGGER `LebedkinAnatolijBD`.`Sales_AFTER_INSERT` AFTER INSERT ON `Sales` FOR EACH ROW
BEGIN
	if Storage.Quantity < Sales.Quantity
    then update Quantity set Quantity=count where count=Sales.Quantity;
    end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
